apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp
        image: ghcr.io/anpt1992/crudapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: crudapp
spec:
  type: NodePort
  selector:
    app: crudapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
