apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-api
  namespace: final-assigment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-inventory-api
  template:
    metadata:
      labels:
        app: product-inventory-api
    spec:
      containers:
      - name: product-inventory-api
        image: ghcr.io/anpt1992/product-inventory-api:v1.0.2
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: POSTGRES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: POSTGRES_CONNECTION_STRING
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
