apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-api
  namespace: final-assigment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-inventory-api
  template:
    metadata:
      labels:
        app: product-inventory-api
    spec:
      containers:
      - name: product-inventory-api
        image: ghcr.io/anpt1992/product-inventory-api:v1.0.0
        ports:
        - containerPort: 9090
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:9090"
        - name: POSTGRES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: POSTGRES_CONNECTION_STRING
